[build]
# default-target = "aarch64-unknown-linux-gnu"
# default-target = "armv7-unknown-linux-gnueabihf"

# [target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"

[target.armv7-unknown-linux-gnueabihf]
# image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:latest"
